package com.spring.user.Enum;

public enum TypeJob {
    INGENIEUR,
    MEDECIN,
    AVOCAT,
    ENSEIGNANT,
    COMPTABLE,
    INFORMATICIEN,
    CONSULTANT,
    AGENT_IMMOBILIER,
    ARTISTE,
    ELECTRICIEN,
    PLOMBIER,
    AGRICULTEUR,
    CHAUFFEUR,
    VENDEUR,
    GESTIONNAIRE,
    ENTREPRENEUR,
    ARCHITECTE,
    ANALYSTE_FINANCIER,
    BANQUIER,
    EMPLOYE_ADMINISTRATIF
}
